### ISSUE TITLE
wrong argument type nil (expected String) --> until I delete environment folders.

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/r10k#533]
I'm getting this error when running `r10k deploy environment -pvt`

Error:   https://gist.github.com/brettswift/9c0cdc45e0f55bf662d6

This gives me an exit code of 1, which causes our cronjob to report a failure to our hipchat room. (ugh!)  yes cron.. still.

This is the resulting permissions of those folders:

``` bash
[root@devcorepptl920 ~]# cd /etc/puppetlabs/code
[root@devcorepptl920 code]# ll
total 16
drwxrwxr-x  9 pe-puppet pe-puppet 4096 Nov  5 15:15 environments
-rw-r--r--  1 peadmin   peadmin    576 Nov  5 08:11 hiera.yaml
drwxr-xr-x 10 root      root      4096 Nov  5 07:36 hostdata
drwxr-xr-x  2 root      root      4096 Oct  6 18:27 modules
[root@devcorepptl920 code]# ll environments/
total 28
drwxr-xr-x 11 root root 4096 Nov  5 07:36 develop
drwxr-xr-x 10 root root 4096 Nov  5 07:38 feature_iptables_to_firewall
drwxr-xr-x 10 root root 4096 Nov  5 07:38 feature_multi_tenancy
drwxr-xr-x 12 root root 4096 Nov  5 07:38 feature_new_2015
drwxr-xr-x 10 root root 4096 Nov  5 07:38 feature_puppet_enc
drwxr-xr-x 11 root root 4096 Nov  5 07:38 nomerge_cutover
drwxr-xr-x 11 root root 4096 Nov  5 07:39 test
[root@devcorepptl920 code]# ll hostdata/
total 32
drwxr-xr-x 4 root root 4096 Nov  5 07:36 feature_oeb_nc_version
drwxr-xr-x 4 root root 4096 Nov  5 07:36 feature_test_puppet_db_dashboard
drwxr-xr-x 4 root root 4096 Nov  5 07:36 hotfix_devcoreappw002_access
drwxr-xr-x 4 root root 4096 Nov  5 07:36 hotfix_m35_access_request
drwxr-xr-x 4 root root 4096 Nov  5 07:36 hotfix_matrix021OE
drwxr-xr-x 4 root root 4096 Nov  5 07:36 hotfix_matrix026OE
drwxr-xr-x 4 root root 4096 Nov  5 07:36 hotfix_matrix037
drwxr-xr-x 4 root root 4096 Nov  5 07:36 live
```

The modules seem to all be filled out. 

One thing to note:  our "hostdata" repository is just a hiera tier, and has no puppetfile, however I still get this error without the -p option. 

r10k.yaml: 

```
[root@devcorepptl920 code]# cat /etc/puppetlabs/r10k/r10k.yaml

---
cachedir: /opt/puppetlabs/server/data/puppetserver/r10k
sources:
  hostdata:
    basedir: /etc/puppetlabs/code/hostdata
    prefix: false
    remote: ssh://git@stash.sjrb.ad:7999/codo/hostdata.git
  puppet:
    basedir: /etc/puppetlabs/code/environments
    prefix: false
    remote: ssh://git@stash.sjrb.ad:7999/~bswift/puppetconfig.git


git:
    private_key: /root/.ssh/r10k/id_rsa
    provider: rugged
```

```
[root@devcorepptl920 code]# puppet --version
4.2.2
[root@devcorepptl920 code]# r10k version
r10k 2.0.3
```

If I delete the hostdata contents (/etc/puppetlabs/code/hostdata),   r10k works. 

Strange?! 

That repo is just this below.   Gemfile, Rakefile, and host folder filled with  .yaml files. 

```
[root@devcorepptl920 code]# ll hostdata/live/
total 24
-rw-r--r-- 1 root root   269 Nov  5 15:26 Gemfile
drwxr-xr-x 2 root root 16384 Nov  5 15:26 host
-rw-r--r-- 1 root root   147 Nov  5 15:26 Rakefile
```

Any idea what is going on here?

**Comment by scotje** [comment]
Can you attach a gist with the output of `r10k deploy environment -p -v debug -t`?

**Comment by adrienthebo** [comment]
This looks likehttps://tickets.puppetlabs.com/browse/RK-175 which was fixed in r10k 2.1.0, try upgrading to have version and see if the error recurs.

**Comment by brettswift** [comment]
Just getting back to this:  I bootstrapped a new puppet master off the new 2015.2.3  which still has the same version of r10k, and I didn't see the issue.  Could be the Puppetfiles reference changed - unfortunately I had a time gap in testing this. 

I'll close this bug.   If I see it again and if 2.1.0 doesn't fix it I'll come back here for help.  

Thanks.
